### ISSUE TITLE
gem not found

### ISSUE THREAD

**Issue by soichih** [sensu-plugins/sensu-plugins-mysql#1]
I've installed the sensu-plugin cert as documented in the README, but I am seeing following error message when I try to install it.

```
$ gem install sensu-plugins-mysql
ERROR:  Could not find a valid gem 'sensu-plugins-mysql' (>= 0) in any repository
```

**Comment by mattyjones** [comment]
https://rubygems.org/gems/sensu-plugins-mysql

**Comment by soichih** [comment]
Thank you for publishing!

But.. I decided to just checkout the entire community plugins repo on all of my machines.
