### ISSUE TITLE
"mysql" ruby gem considered deprecated

### ISSUE THREAD

**Issue by luxifer** [sensu-plugins/sensu-plugins-mysql#12]
According to https://rubygems.org/gems/mysql the `mysql` gem is considered deprecated. 

> Please note that tmtm (Tomita Mashahiro) has deprecated development of this extension and only update it for bug fixes.

Also I noticed that this plugin also required the `mysql2` gem. Why both?

**Comment by eheydrick** [comment]
metrics-mysql-graphite.rb uses `mysql2`. We should probably move to that given that `mysql` is deprecated.

**Comment by dcharleston** [comment]
Opened https://github.com/sensu-plugins/sensu-plugins-mysql/pull/13 to update check-mysql-connections

**Comment by sstarcher** [comment]
#13 should close this
