### ISSUE TITLE
Replication check has a collision with arguments

### ISSUE THREAD

**Issue by tjhanley** [sensu-plugins/sensu-plugins-mysql#15]
`-h` for host collides with `-h` for help. 

https://github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/check-mysql-replication-status.rb#L32
&
https://github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/check-mysql-replication-status.rb#L81

Check fails as a result.
> CheckMysqlReplicationStatus UNKNOWN: Must specify host, user, password

**Comment by eheydrick** [comment]
The `-h|--help` flag is definitely not needed as OptParser implicitly adds the `--help` option. We should remove that flag. That said, the `-h` flag does take the hostname.

**Comment by sstarcher** [comment]
Removed option.  -h will be host and --help will be help.

https://github.com/sensu-plugins/sensu-plugins-mysql/commit/413f0f0d889562a15bc720be6f60ae5b5fe12caa
