### ISSUE TITLE
Update requirement mysql2

### ISSUE THREAD

**Issue by corro** [sensu-plugins/sensu-plugins-mysql#16]
Currently required mysql2 version 0.3.18 does not properly close mysql connections (see https://github.com/brianmario/mysql2/issues/606). This leads to the effect, that metrics-mysql-graphite.rb always reports an aborted client every check. This issue should be fixed in newer version of mysql2.

**Comment by sstarcher** [comment]
@corro we just removed mysql2 in favor of ruby-mysql

**Comment by corro** [comment]
This issue should be resolved with the change to ruby-mysql. Unfortunately the client connection is still not properly closed in metrics-mysql-graphite.rb. See pull request https://github.com/sensu-plugins/sensu-plugins-mysql/pull/23.
