### ISSUE TITLE
version `libmysqlclient_20.2' not found

### ISSUE THREAD

**Issue by Craigeous** [sensu-plugins/sensu-plugins-mysql#41]
Getting this message when running the slave status check...

> /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/lib64/mysql/libmysqlclient.so.20: version `libmysqlclient_20.2' not found (required by /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/mysql-2.9.1/lib/mysql/mysql_api.so) - /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/mysql-2.9.1/lib/mysql/mysql_api.so (LoadError)
from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/mysql-2.9.1/lib/mysql.rb:6:in `rescue in <top (required)>'
from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/mysql-2.9.1/lib/mysql.rb:2:in `<top (required)>'
from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-mysql-0.0.4/bin/check-mysql-replication-status.rb:27:in `<top (required)>'
from /opt/sensu/embedded/bin/check-mysql-replication-status.rb:22:in `load'
from /opt/sensu/embedded/bin/check-mysql-replication-status.rb:22:in `<main>'
Usage: /opt/sensu/embedded/bin/check-mysql-replication-status.rb (options)

It seems to be working on all servers except the ones that I removed the older version of mysql connector for python and installed a newer version that worked with the 1.6.4 mysql utilities.

I found the libmysqlclient.so.20.2.0 (i think) in an older version of mysql that i extracted and put in the /usr/lib64/mysql directory... Didn't help, but looking at the file i see it's calling for the _20.2 in the so.20 file not the one I put in there.  

So, I'm not really sure how to go about resolving this.  I have tried reinstalling the plugin the mysql2 gem.  I cannot reinstall mysql without jumping through a lot of hoops.

any idea?

**Comment by Ramesh7** [comment]
Hi Craigeous,

Please uninstall mysql and mysql2 gem and reinstall it. I have come across same issue and it worked for me. Hope this will help you.

Thanks
Ramesh

**Comment by eheydrick** [comment]
@Craigeous are you still having problems?

**Comment by eheydrick** [comment]
Closing due to age. Feel free to re-open if this is still an issue.
