### ISSUE TITLE
Where is "mysql-metrics.json"?

### ISSUE THREAD

**Issue by lashomb** [sensu-plugins/sensu-plugins-mysql#42]
In https://github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/metrics-mysql.rb it mentions:

  MySQL 'hostname', 'username', and 'password' must be
  specified in a config file in /etc/sensu/conf.d.
  See mysql-metrics.json for an example.

Where is "mysql-metrics.json"?

**Comment by eheydrick** [comment]
There's an example in the README: 

metrics-mysql:
```
{
    "mysql":{
        "hostname": "localhost",
        "username": "sensu_user",
        "password": "sensu_user_pass"
    }
}
```
