### ISSUE TITLE
check-mysql-status.rb reuses short arguments

### ISSUE THREAD

**Issue by funjon** [sensu-plugins/sensu-plugins-mysql#43]
https://github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/check-mysql-status.rb#L45
https://github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/check-mysql-status.rb#L47

both claim -c. Only the latter seems to work.

**Comment by eheydrick** [comment]
Whoops, one of those should change to `-C`. Probably the first one.

**Comment by majormoses** [comment]
@funjon can you submit a pr with the suggested change?
