### ISSUE TITLE
Multi Source Replication check is not working for multi source in MySQL 5.7

### ISSUE THREAD

**Issue by eyalmadar** [sensu-plugins/sensu-plugins-mysql#48]
Hi,
In continuing to the conversation in the link below, 
This is a highly desired feature and I would like to know if you have an estimation when it will be pushed.
https://github.com/sensu-plugins/sensu-plugins-mysql/commit/68aef5b5ee20c4d880deafd5aeb7c2a0cad9099c#diff-ebbf24d20eee63e56e38316772592ed5R109

Thanks,
Eyal

**Comment by majormoses** [comment]
I would be more than happy to accept a PR for it, could you take a crack at it?

**Comment by ndelic0** [comment]
Please have a look on https://github.com/ndelic0/sensu-plugins-mysql/blob/mysql-msr-replication-check/bin/check-mysql-msr-replication-status.rb

**Comment by majormoses** [comment]
nice, can you create a pull request with it? Can you please include a [changelog entry](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md) and a [testing artifact](https://github.com/sensu-plugins/community/blob/master/PULL_REQUEST_PROCESS.md#7-testing-artifacts)?

**Comment by majormoses** [comment]
When you have multi source there is now a separate check for it thanks @ndelic0 for putting that together in #69 

released: https://rubygems.org/gems/sensu-plugins-mysql/versions/2.3.0
