### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by zerOnepal** [sensu-plugins/sensu-plugins-mysql#5]
I been going through the plugins and bit confused.

..wish there exists some docs/README

For the following option on [check-mysql-disk.rb](https://github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/check-mysql-disk.rb#L38-L41).. what does the size implies ?? 
I guess total expected allocated database size, is it ??  
```
option :size,
         short: '-s',
         long: '--size=VALUE',
         description: 'Database size'
```
Looking for some examples on the plugins.rb files..

**Comment by eheydrick** [comment]
We'd love to improve the documentation. If you have any suggestions feel free to open a PR.

**Comment by arianf** [comment]
@thapakazi Did you ever find out what format the size value is expecting? Is it GB, MB, KB? Can't figure it out....

**Comment by thapakazi** [comment]
I don't remember much, if I found the answer @arianf 
These days I have switch from world of **sensu** to [Prometheus](https://github.com/sensu-plugins/sensu-plugins-mysql/issues/5#issuecomment-289606872) :neckbeard: and I am loving it more :hear_no_evil:
