### ISSUE TITLE
[DOCUMENTATION] what user privs do the various checks require?

### ISSUE THREAD

**Issue by rwillmer** [sensu-plugins/sensu-plugins-mysql#50]
I'd like to create a sensu user in the mysql database being monitored with the minimum number of privileges for the various commands. What is that minimum needed to be useful?

**Comment by majormoses** [comment]
good question I would honestly have to dig through each check and all the upstream code to know for sure. If I have enough time this weekend I will try to see what I can find.

**Comment by majormoses** [comment]
The easiest way would be start with no privs and slowly add privs as it fails until you can do what is needed. We should definitely figure this out and document it.

**Comment by majormoses** [comment]
List of checks
- [ ] check-mysql-alive.rb
- [ ] check-mysql-connections.rb
- [ ] check-mysql-disk.rb
- [ ] check-mysql-innodb-lock.rb
- [ ] check-mysql-query-result-count.rb
- [ ] check-mysql-replication-status.rb
- [ ] check-mysql-status.rb
- [ ] check-mysql-threads.rb
- [ ] metrics-mysql-graphite.rb
- [ ] metrics-mysql-processes.rb
- [ ] metrics-mysql-query-result-count.rb
- [ ] metrics-mysql-raw.rb
- [ ] metrics-mysql.rb
- [ ]

**Comment by majormoses** [comment]
@rwillmer Those are what they seem to be from my quick tests and quick scan of code, other than `check-mysql-disk.rb` I am fairly confident what I outlined is right. Let me know if you see any deviations from this as I will put together a PR to document this as its super helpful and we should not encourage people to give sensu root privs into your database...

**Comment by majormoses** [comment]
If I had to I would say `REPLICATION CLIENT` seems better to me in `check-mysql-replication-status.rb`. I know I would never give `SUPER` to any monitoring system...

**Comment by majormoses** [comment]
You can also check and they return reasonable error messages for example:
```
$ ./bin/check-mysql-replication-status.rb -h 172.17.0.2 -u sensu -p sensu
CheckMysqlReplicationStatus CRITICAL: Error code: 1227 Error message: Access denied; you need (at least one of) the SUPER, REPLICATION CLIENT privilege(s) for this operation SQLSTATE: 42000
```

**Comment by majormoses** [comment]
@rwillmer I have added documentation in #52 let me know if there is anything else you think I should add

**Comment by rwillmer** [comment]
Thanks, that's perfect.
