### ISSUE TITLE
check-mysql-disk.rb size should be a required option

### ISSUE THREAD

**Issue by majormoses** [sensu-plugins/sensu-plugins-mysql#51]
I setup a very simple docker test using this:
```
docker run --name sensu-test -e MYSQL_ROOT_PASSWORD="SOME_ROOT_PASS" mysql:5.7
# inside docker container
mysql> GRANT SELECT ON *.* TO 'sensu'@'172.17.0.1' IDENTIFIED BY 'sensu';
mysql> FLUSH PRIVILEGES;
````

when running the following command it `critical`s incorrectly and probably should emit an `unknown`:
```
$ ./bin/check-mysql-disk.rb -h 172.17.0.2 -u sensu -p sensu
CheckMysqlDisk CRITICAL: Database size exceeds critical threshold: DB size: 0.01, disk use: Infinity%
```

I have not inspected the sql very but I would guess that it is right and we need some special logic to deal with disk in use as infinity

**Comment by rwillmer** [comment]
This is user error, rather than a docker problem. You need to specify the max db size you expect; no default is provided.

Add a --size parameter to your use of check-mysql-disk.rb, and you'll get a more informative message from it.

**Comment by majormoses** [comment]
Hmm I thought I attempted that and it had no difference, I will give it another shot.

**Comment by majormoses** [comment]
I see, I had to read the code to understand that disk size is really required even though it is not designated as such. I think we need to enhance this experience to make it a required option as there is no value in its current state checking if a number is larger than infinite.

This will never trigger: https://github.com/sensu-plugins/sensu-plugins-mysql/blob/2.1.0/bin/check-mysql-disk.rb#L83-L85 as cast it as a float therefore not making it nil: https://github.com/sensu-plugins/sensu-plugins-mysql/blob/2.1.0/bin/check-mysql-disk.rb#L79
```
$ irb
irb(main):001:0> a = nil
=> nil
irb(main):002:0> a.to_f
=> 0.0
```

I will put a PR together to address this...

**Comment by majormoses** [comment]
addressing via #55 @rwillmer if you can look and validate I can release this to avoid confusion in the future.

**Comment by rwillmer** [comment]
Looks good to me.
