### ISSUE TITLE
Add socket param to INI file

### ISSUE THREAD

**Issue by hanynowsky** [sensu-plugins/sensu-plugins-mysql#6]
we populate the /etc/sensu/my.cnf with MySQL user and pass. But usually we need to point the path of used MySQL socket which is not always /var/lib/mysql/mysql.sock
- Thus, enabling socket param in /etc/sensu/my.cnf is the best option (Since using --socket option from sensu server is impossible when differents clients have different mysql paths):
  Just this would do:

``` ruby

def run
    if config[:ini]
      ini = IniFile.load(config[:ini])
      section = ini['client']
      db_user = section['user']
      db_pass = section['password']
      db_socket = section['socket']
    else
      db_user = config[:user]
      db_pass = config[:password]
      db_socket = config[:socket]
    end

    begin
      db = Mysql.real_connect(config[:hostname], db_user, db_pass, config[:database], config[:port].to_i, db_socket)

```

**Comment by majormoses** [comment]
@hanynowsky sorry for the lack of response here...

Is there any reason you can not set this via cli args? From a quick scan of the code this is already supported to mix and match cli and ini with the exception of username/pass which those are honestly the only things I see value in having not exposed via cli args.

**Comment by hanynowsky** [comment]
@majormoses It is easier and more practical if you're using a CM tool like Chef or Ansible to have socket defined in the my.cnf file.
Yet as you said, we've been doing this way:
--socket `cat /etc/sensu/my.cnf | grep socket | cut -d= -f2` :::mysql.statusoptions|:::",

**Comment by majormoses** [comment]
OK that makes sense, was primarily checking to see if you thought you were blocked or not. I am torn on whether to support making every option available in the ini file. 

The good:
- makes it arguably easier for deployment

The Bad:
- people will add features (flags) and not add support for the options and will create more PRs being opened.

@eheydrick thoughts? My stance is if we go beyond strict credentials in ini then we open up more issues but it is arguably easier (the way I have it set up in my chef env managing cli args for sensu is just as easy as managing a config file)

**Comment by eheydrick** [comment]
I'd favor using the cli flags. That's what they are there for. With CM you can set up your checks for whatever is on the box.

**Comment by majormoses** [comment]
@hanynowsky If there is something we are missing please reply back and we can continue discussion but I don't see value in this.
