### ISSUE TITLE
Sensu 0.29 & ruby 2.4 broke mysql dependency 

### ISSUE THREAD

**Issue by johntdyer** [sensu-plugins/sensu-plugins-mysql#60]
Appears that Sensu 0.29, which upgraded to Ruby 2.4, has broken support for ruby-mysql...

https://stackoverflow.com/questions/41520996/mysql-gem-install-error-on-ruby-2-4

**Comment by sodabrew** [comment]
This plugin uses `ruby-mysql`, a pure Ruby client library, and not the `mysql` gem. Your SO link refers to problems with the `mysql` gem. Are you directly experiencing a problem installing Sensu at this time?

**Comment by johntdyer** [comment]
@sodabrew , I guess i was using the other mysql gem....     

`gem install mysql` != `gem install ruby-mysql`

honestly, I never knew that until today that there were two mysql gems.....

**Comment by sodabrew** [comment]
Three in fact! I maintain the mysql2 gem :)

**Comment by johntdyer** [comment]
I knew about mysql2 and mysql, I just didnt know about the pure ruby one... :) thanks !
